Feature/contact us
ifElse-Code/projectBlog pull request #36
Opened 2020-09-26 22:45 UTC by DandiKandie

Html content for the Contact Us page. 
Will complete the CSS styles for it and submit new push request.

2020-09-26 23:12 UTC, Noel-Garces08 requested changes

2020-09-26 23:12 UTC, Noel-Garces08 commented on views/contact.ejs
> +</main>
- The lines I am commenting on are the only lines you need, no need for the boilerplate.

- Make sure to link your css file in the main-layout.ejs right above the font awesome link.

2020-09-28 14:33 UTC, ChrisOrmzy commented
You don't need the html boiler plate

2020-09-28 15:12 UTC, DandiKandie commented
Boilerplate removed.. not sure what else needs to be done..

2020-09-28 17:07 UTC, Noel-Garces08 approved these changes

2020-09-28 17:08 UTC, merged