created 404 error page, corresponding css file and an image folder
ifElse-Code/projectBlog pull request #52
Opened 2020-09-28 21:10 UTC by ChrisOrmzy

Created 404 page and corrsponding css file.
Created image folder to hold a holding image for 404 page.

2020-09-28 22:57 UTC, scholtz-gnome requested changes
If you can just remove that ul in 404.ejs, then all should be good to go.

2020-09-28 22:57 UTC, scholtz-gnome commented on views/404.ejs
> +    </ul>
Thanks for this Chris! :) I don't think you need this ul here as the main nav will still be visible and accessible on the left of the screen.

2020-09-30 12:19 UTC, ifElse-Code approved these changes

2020-09-30 18:36 UTC, scholtz-gnome approved these changes
Thanks Chris!

2020-09-30 18:36 UTC, merged